# CentOS Vagrantfile
Vagrant.configure("2") do |config|
  # Use the official CentOS Stream 9 box from EuroLinux
  config.vm.box = "eurolinux-vagrant/centos-stream-9"

  # Network configuration
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"
end
