# Ubuntu Vagrantfile with custom specs

Vagrant.configure("2") do |config|
  # Use the official Ubuntu 20.04 LTS box
  config.vm.box = "ubuntu/focal64"

  # Network configurations
  config.vm.network "private_network", ip: "192.168.56.26"
  config.vm.network "public_network"

  # VM resource specifications
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1600"
  end
end
