# CentOS Vagrantfile with custom specs and provisioning for Inner Peace website from tooplate.com

Vagrant.configure("2") do |config|
  # Use the official CentOS Stream 9 box from EuroLinux
  config.vm.box = "eurolinux-vagrant/centos-stream-9"

  # Network configurations
  config.vm.network "private_network", ip: "192.168.56.28"
  config.vm.network "public_network"

  # VM resource specifications
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  # Provisioning script to set up Apache and deploy website
  config.vm.provision "shell", inline: <<-SHELL
    yum install httpd wget unzip vim -y
    systemctl start httpd
    systemctl enable httpd
    mkdir -p /tmp/peace
    cd /tmp/peace
    wget https://www.tooplate.com/zip-templates/2143_inner_peace.zip
    unzip -o 2143_inner_peace.zip
    cp -r 2143_inner_peace/* /var/www/html/
    systemctl restart httpd
    cd /tmp/
    rm -rf /tmp/peace
  SHELL
end
