# CentOS Vagrantfile with custom specs

Vagrant.configure("2") do |config|
  # Use the official CentOS Stream 9 box from EuroLinux
  config.vm.box = "eurolinux-vagrant/centos-stream-9"

  # Network configurations
  config.vm.network "private_network", ip: "192.168.56.22"
  config.vm.network "public_network"
  
  # VM resource specifications
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
